apiVersion: v1
kind: Service
metadata:
  name: {{ include "chromadb-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chromadb-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "chromadb-helm.selectorLabels" . | nindent 4 }}
